# Source: jxboot-helmfile-resources/templates/docker-cfg-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-docker-cfg
spec:
  backendType: gcpSecretsManager
  projectId: jx-development
  data:
  - name: jenkins-docker-cfg
    key: jenkins-docker-cfg
    property: config.json
    version: latest
  template:
    type: Opaque
