# Source: jxboot-helmfile-resources/templates/environments.yaml
apiVersion: jenkins.io/v1
kind: Environment
metadata:
  labels:
    env: "dev"
    team: jx
    gitops.jenkins-x.io/pipeline: 'environment'
  name: "dev"
  namespace: jx
spec:
  kind: Development
  label: Development
  namespace: jx
  promotionStrategy: Never
  webHookEngine: "Lighthouse"
  teamSettings:
    appsRepository: http://chartmuseum.jenkins-x.io
    buildPackRef: "master"
    buildPackUrl: "https://github.com/jenkins-x/jxr-packs-kubernetes.git"
    defaultScheduler:
      apiVersion: jenkins.io/v1
      kind: Scheduler
      name: default
    dockerRegistryOrg: "jx-development"
    envOrganisation: cb-kubecd
    gitServer: https://github.com
    gitPublic: true
    helmTemplate: true
    kubeProvider: "gke"
    pipelineUsername: ""
    pipelineUserEmail: ""
    prowConfig: Scheduler
    importMode: YAML
    promotionEngine: Prow
    prowEngine: Tekton
    versionStreamUrl: "https://github.com/jenkins-x/jxr-versions.git"
    versionStreamRef: "master"
    useGitOps: true
  source:
    url: https://github.com/cb-kubecd/jr-dev9
