# Source: jxboot-helmfile-resources/templates/maven-settings-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-maven-settings
spec:
  backendType: gcpSecretsManager
  projectId: jx-development
  data:
  - name: jenkins-maven-settings
    key: jenkins-maven-settings
    property: settings.xml
    version: latest
  - name: jenkins-maven-settings
    key: jenkins-maven-settings
    property: settings-security.xml
    version: latest
  template:
    type: Opaque
