# Source: jxboot-helmfile-resources/templates/npm-token-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-npm-token
spec:
  backendType: gcpSecretsManager
  projectId: jx-development
  data:
  - name: jenkins-npm-token
    key: secret/data/jenkins/npm
    property: token
    version: latest
  template:
    type: Opaque
