# Source: jxboot-helmfile-resources/templates/npm-token-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-npm-token
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
spec:
  backendType: gsm
  data:
  - name: token
    key: secret/data/jenkins/npm
    property: token
  template:
    type: Opaque
