# Source: jxboot-helmfile-resources/charts/controllerbuild/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controllerbuild-jx
  namespace: jx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: controllerbuild-jx
subjects:
- kind: ServiceAccount
  name: jxboot-helmfile-resources-controllerbuild
  namespace: jx
