# Source: nexus/templates/secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: nexus
spec:
  backendType: gcpSecretsManager
  data:
  - name: password
    key: jx-adminUser-password
    property: password
  template:
    metadata:
      labels:
        app: nexus-nexus
        chart: "nexus-0.1.30"
        release: "nexus"
        heritage: "Helm"
    type: Opaque
