# Source: kubernetes-external-secrets/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-external-secrets
  namespace: "external-secrets"
  annotations:
    iam.gke.io/gcp-service-account: jrtest9-sm@jx-development.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-4.0.0
    app.kubernetes.io/instance: kubernetes-external-secrets
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'environment'
