apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SecretMapping
spec:
  secrets:
  - name: lighthouse-hmac-token
    backendType: gcpSecretsManager
    project: jx-development
    mappings:
    - name: hmac
      key: lighthouse-hmac-token
  - name: lighthouse-oauth-token
    backendType: gcpSecretsManager
    project: jx-development
    mappings:
    - name: oauth
      key: jx-pipelineUser-token
  - name: lighthouse-oauth-token
    backendType: gcpSecretsManager
    project: jx-development
    mappings:
    - name: oauth
      key: jx-pipelineUser-token
  - name: nexus
    backendType: gcpSecretsManager
    project: jx-development
    mappings:
    - name: password
      key: jx-adminUser-password
  - name: jenkins-x-chartmuseum
    backendType: gcpSecretsManager
    project: jx-development
    mappings:
    - name: BASIC_AUTH_USER
      key: jx-adminUser-username
    - name: BASIC_AUTH_PASS
      key: jx-adminUser-password
  defaultBackendType: gcpSecretsManager

