# Source: tekton/templates/250-git-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: knative-git-user-pass
spec:
  backendType: gcpSecretsManager
  projectId: jx-development
  data:
  - name: knative-git-user-pass
    key: knative-git-user-pass
    property: password
    version: latest
  - name: knative-git-user-pass
    key: knative-git-user-pass
    property: username
    version: latest
  template:
    metadata:
      annotations:
        tekton.dev/git-0: "https://github.com"
    type: kubernetes.io/basic-auth
