# Source: tekton/templates/250-docker-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: knative-docker-user-pass
spec:
  backendType: gcpSecretsManager
  projectId: jx-development
  data:
  - name: knative-docker-user-pass
    key: knative-docker-user-pass
    property: password
    version: latest
  - name: knative-docker-user-pass
    key: knative-docker-user-pass
    property: username
    version: latest
  template:
    metadata:
      annotations:
        tekton.dev/docker-0: ""
    type: kubernetes.io/basic-auth
