# Source: chartmuseum/templates/secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-x-chartmuseum
spec:
  backendType: gcpSecretsManager
  data:
  - name: BASIC_AUTH_PASS
    key: jx-adminUser-password
    property: BASIC_AUTH_PASS
  - name: BASIC_AUTH_USER
    key: jx-adminUser-username
    property: BASIC_AUTH_USER
  template:
    metadata:
      annotations:
        jenkins.io/credentials-keybinding-password: BASIC_AUTH_PASS
        jenkins.io/credentials-keybinding-username: BASIC_AUTH_USER
      labels:
        jenkins.io/credentials-type: usernamePassword
        app: chartmuseum
        chart: chartmuseum-1.1.7
        heritage: "Helm"
        release: "chartmuseum"
    type: Opaque
