# Source: lighthouse/templates/hmacsecret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: lighthouse-hmac-token
spec:
  backendType: gcpSecretsManager
  projectId: jx-development
  data:
  - name: lighthouse-hmac-token
    key: lighthouse-hmac-token
    property: hmac
    version: latest
  template:
    metadata:
      labels:
        app: lighthouse-lighthouse
        chart: "lighthouse-0.0.633"
        release: "lighthouse"
        heritage: "Helm"
    type: Opaque
