# Source: lighthouse/templates/oauthsecret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: lighthouse-oauth-token
spec:
  backendType: gcpSecretsManager
  projectId: jx-development
  data:
  - name: lighthouse-oauth-token
    key: jx-pipelineUser-token
    property: oauth
    version: latest
  template:
    metadata:
      labels:
        app: lighthouse-lighthouse
        chart: "lighthouse-0.0.633"
        release: "lighthouse"
        heritage: "Helm"
    type: Opaque
